Pip package for `tutorial-vm`
talmolab/cosyne_vm pull request #5
Opened 2024-11-05 03:09 UTC by eberrigan

- `pyproject.toml` sets up pip package
- modules are moved inside `tutorial_vm` directory

2024-11-06 19:33 UTC, gitttt-1234 commented on .github/workflows/build-and-test-pip.yml
> +
upload archive to access later

2024-11-06 19:34 UTC, gitttt-1234 commented on .github/workflows/build-and-publish-manual.yml
> +
possibly have input of archive from build and test stage

2025-02-18 21:27 UTC, 7174Andy reviewed
```
# Change to the directory where the Python script is located
cd /home/$USER_NAME/cosyne_vm

# Check if the scripts need to be updated
if [ "$UPDATE_COSYNE_VM_REPO" = "True" ]; then
    echo "Updating the cosyne_vm repository..."
    git pull
    /opt/conda/bin/python3 -m pip install -r requirements.txt
fi

# We need to run the Python script with sudo -u $USER_NAME for the CRD command to work
# Listen for messages on pubsub topic hostname (need to use correct Python installation)
sudo -u $USER_NAME /opt/conda/bin/python3 subscribe_instance.py \
    --project_id $PROJECT_ID \
    --db_instance_id $DB_INSTANCE \
    --db_id $DB_NAME \
    --db_table_name $DB_TABLE &

# Update the inuse status of the VM whenever sleap opens/closes
/opt/conda/bin/python3 update_inuse_status.py \
    --project_id $PROJECT_ID \
    --db_instance_id $DB_INSTANCE \
    --db_id $DB_NAME \
    --db_table_name $DB_TABLE &
```

This is part of the `start_up.sh` script for each VM to run right after creation of a VM instance. This part of the code enable the VM instance to listen to any changes in the database by subscribing to the topic in Pub/Sub. 

 Is there a way to run the `subscribe_instance.py` and `update_inuse_status.py` if we publish this repo in to Pip package?

Source: https://github.com/talmolab/vmassign/blob/main/vmassign/vm/manage/start_up.sh

2025-02-18 21:56 UTC, eberrigan commented
> Everything looks good! However, I have one concern:
> 
> ```
> # Change to the directory where the Python script is located
> cd /home/$USER_NAME/cosyne_vm
> 
> # Check if the scripts need to be updated
> if [ "$UPDATE_COSYNE_VM_REPO" = "True" ]; then
>     echo "Updating the cosyne_vm repository..."
>     git pull
>     /opt/conda/bin/python3 -m pip install -r requirements.txt
> fi
> 
> # We need to run the Python script with sudo -u $USER_NAME for the CRD command to work
> # Listen for messages on pubsub topic hostname (need to use correct Python installation)
> sudo -u $USER_NAME /opt/conda/bin/python3 subscribe_instance.py \
>     --project_id $PROJECT_ID \
>     --db_instance_id $DB_INSTANCE \
>     --db_id $DB_NAME \
>     --db_table_name $DB_TABLE &
> 
> # Update the inuse status of the VM whenever sleap opens/closes
> /opt/conda/bin/python3 update_inuse_status.py \
>     --project_id $PROJECT_ID \
>     --db_instance_id $DB_INSTANCE \
>     --db_id $DB_NAME \
>     --db_table_name $DB_TABLE &
> ```
> 
> This is part of the `start_up.sh` script for each VM to run right after creation of a VM instance. This part of the code enable the VM instance to listen to any changes in the database by subscribing to the topic in Pub/Sub.
> 
> Is there a way to run the `subscribe_instance.py` and `update_inuse_status.py` on a bash script if we publish this repo in to Pip package?
> 
> Source: https://github.com/talmolab/vmassign/blob/main/vmassign/vm/manage/start_up.sh

This should actually be easier with a pip package! SO now we will do something like 1. make env for vmassign that has our pip package 2. use commands where as before we had to clone the source code etc.

2025-02-18 21:58 UTC, 7174Andy approved these changes
Sounds good! I think it is good to merge.

2025-02-18 23:23 UTC, roomrys requested changes
Some comments on improving the workflows and also request to remove debug code.

2025-02-18 23:23 UTC, roomrys commented on .github/workflows/publish-pip.yml
It would be a good idea to require the build-and-test-pip.yml to run and pass before this workflow can run (and then releases that latest built package).

2025-02-18 23:23 UTC, roomrys commented on .github/workflows/build-and-test-pip.yml
> +      uses: actions/checkout@v4
So we do need the tests folder, but having all the code checked-out can lead to false positive import tests (see [b8005](https://github.com/talmolab/cosyne_vm/pull/5/commits/b8005b74e0eaa3488a4ae2ad0f15e43aecb174d1)). Maybe there is a way to just move the tests folder and change that to our working directory?

2025-02-18 23:23 UTC, roomrys commented on tests/test_imports.py
> +    test_import()
With the changes in [b8005](https://github.com/talmolab/cosyne_vm/pull/5/commits/b8005b74e0eaa3488a4ae2ad0f15e43aecb174d1), I believe we can remove this `pythonpath` manipulation. Also we don't really need debug code in here.
```suggestion
```

2025-02-19 18:10 UTC, eberrigan commented on .github/workflows/publish-pip.yml
will make these changes in separate PR

2025-02-19 18:10 UTC, merged